"""Add video thumbnails support

Revision ID: fef8a2c2eebc
Revises: 3ab08c05ac2e
Create Date: 2026-01-07 09:54:16.139473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fef8a2c2eebc'
down_revision: Union[str, None] = '3ab08c05ac2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_thumbnails', sa.Column('is_auto_generated', sa.Boolean(), nullable=False))
    op.add_column('video_thumbnails', sa.Column('is_selected', sa.Boolean(), nullable=False))
    op.alter_column('video_thumbnails', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ix_video_thumbnails_video_id', table_name='video_thumbnails')
    op.drop_column('video_thumbnails', 'sequence')
    op.drop_column('video_thumbnails', 'width')
    op.drop_column('video_thumbnails', 'height')
    op.drop_column('video_thumbnails', 'file_size')
    op.drop_column('video_thumbnails', 'timestamp')
    op.add_column('videos', sa.Column('thumbnail_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_path')
    op.add_column('video_thumbnails', sa.Column('timestamp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('video_thumbnails', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_thumbnails', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('video_thumbnails', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('video_thumbnails', sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_video_thumbnails_video_id', 'video_thumbnails', ['video_id'], unique=False)
    op.alter_column('video_thumbnails', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('video_thumbnails', 'is_selected')
    op.drop_column('video_thumbnails', 'is_auto_generated')
    # ### end Alembic commands ###
